version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.x
  build:
    commands:
      - export BUCKET=my_bucket_name
      - aws cloudformation package --template-file template.yml --s3-bucket my_bucket_name --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
